export const FETCH_STORE_STOCK_REQUEST = "FETCH_STORE_STOCK_REQUEST";
export const FETCH_STORE_STOCK_SUCCESS = "FETCH_STORE_STOCK_SUCCESS";
export const FETCH_STORE_STOCK_FAILURE = "FETCH_STORE_STOCK_FAILURE";
export const ADD_STORE_STOCK_REQUEST = "ADD_STORE_STOCK_REQUEST";
export const ADD_STORE_STOCK_SUCCESS = "ADD_STORE_STOCK_SUCCESS";
export const ADD_STORE_STOCK_FAILURE = "ADD_STORE_STOCK_FAILURE";
export const UPDATE_STORE_STOCK_REQUEST = "UPDATE_STORE_STOCK_REQUEST";
export const UPDATE_STORE_STOCK_SUCCESS = "UPDATE_STORE_STOCK_SUCCESS";
export const UPDATE_STORE_STOCK_FAILURE = "UPDATE_STORE_STOCK_FAILURE";





